export enum ODS_ENUM {
    FIN_POBREZA = 'Fin de la pobreza',
    HAMBRE_CERO = 'Hambre cero',
    SALUD_BIENESTAR = 'Salud y bienestar',
    EDUCACION_DE_CALIDAD = 'Educación de calidad',
    IGUALDAD_DE_GENERO = 'Igualdad de género',
    AGUA_LIMPIA_Y_SANEAMIENTO = 'Agua limpia y saneamiento',
    ENERGIA_ASEQUIBLE_Y_NO_CONTAMINANTE = 'Energía asequible y no contaminante',
    TRABAJO_DECENTE_Y_CRECIMIENTO_ECONOMICO = 'Trabajo decente y crecimiento económico',
    INDUSTRIA_INNOVACION_INFRAESTRUCTURAS = 'Industria, innovación e infraestructura',
    REDUCCION_DE_DESIGUALDADES = 'Reducción de las desigualdades',
    CIUDADES_Y_COMUNIDADES_SOSTENIBLES = 'Ciudades y comunidades sostenibles',
    PRODUCCION_Y_CONSUMO_RESPONSABLES = 'Producción y consumo responsables',
    ACCION_POR_EL_CLIMA = 'Acción por el clima',
    VIDA_SUBMARINA = 'Vida submarina',
    VIDA_EN_TERRITORIO = 'Vida en la tierra',
    PAZ_Y_JUSTICIA = 'Paz, justicia e instituciones sólidas',
    ALIANZAS = 'Alianzas para lograr los objetivos',
  }