name: solidarianid

services:
  postgres:
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=sonar
    container_name: solidarianid-postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - solidarianetwork

  nestjs:
    build:
      context: ..
      dockerfile: cd-ci/Dockerfile
    container_name: solidarianid-nestjs
    environment:
      - PORT=3000
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    volumes:
      - ../src:/app/src
    networks:
      - solidarianetwork

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: solidarianid-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - postgres
    networks:
      - solidarianetwork

  sonarqube:
    image: sonarqube:10-community
    container_name: solidarianid-sonarqube
    depends_on:
      - postgres
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/sonar
      SONAR_JDBC_USERNAME: postgres
      SONAR_JDBC_PASSWORD: postgres
    ports:
      - "9000:9000"
    networks:
      - solidarianetwork
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_temp:
  sonar_db:
  sonar_db_data:

networks:
  solidarianetwork:
    driver: bridge