GET http://localhost:3002/aa3deb38-d1d2-47e3-8178-7da4bbec5a32
Cookie: accessToken=j%3A%7B%22accessToken%22%3A%22eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDZlOThhYS03Zjg3LTRhZmYtOTc5NS0wZThlZTJlMDNkYjUiLCJlbWFpbCI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwicm9sZSI6InJlZ2lzdGVyZWQiLCJpYXQiOjE3MzU4MzIyMTAsImV4cCI6MTczNTgzNTgxMCwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.QmKScE7H3cAgrUZXlpliAyjssOjr_LWf8CGtVwhtBW4%22%2C%22refreshToken%22%3A%22eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDZlOThhYS03Zjg3LTRhZmYtOTc5NS0wZThlZTJlMDNkYjUiLCJyZWZyZXNoVG9rZW5JZCI6IjUwMDc2ZGQyLTE3NjEtNGZkMi05YjEyLTU3MzkwNjQzYWVhNiIsImlhdCI6MTczNTgzMjIxMCwiZXhwIjoxNzM1OTE4NjEwLCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.hnvUOtSFMGldMSoDTTn8d6netTZCs9g729LDW6AtG5A%22%7D; Path=/; HttpOnly; Secure; SameSite=Strict
### Check whether the ID is an UUID: