GET http://localhost:3002/aa3deb38-d1d2-47e3-8178-7da4bbec5a32
Cookie: accessToken=j%3A%7B%22accessToken%22%3A%22eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiNjY1NGJjMy1kMWZiLTQ1YmEtOTVlNS1hMzlhYjFkN2VjYzQiLCJlbWFpbCI6ImpvaG4uZG9lMkBleGFtcGxlLmNvbSIsImlhdCI6MTczNTgwOTIwNiwiZXhwIjoxNzM1ODEyODA2LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.oYryuMPmz3SFGLFF9CwVi7WMaLhGlOPoWjjz34QXSBc%22%2C%22refreshToken%22%3A%22eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiNjY1NGJjMy1kMWZiLTQ1YmEtOTVlNS1hMzlhYjFkN2VjYzQiLCJpYXQiOjE3MzU4MDkyMDYsImV4cCI6MTczNTg5NTYwNiwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.3EPP9hCkw1_as9dzT7zAfjXZO2i9qsC0ekwakWa-UBc%22%7D; Path=/; HttpOnly; Secure; SameSite=Strict
### Check whether the ID is an UUID: