GET http://localhost:3002/
Cookie: accessToken=j%3A%7B%22accessToken%22%3A%22eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiMTJhODIwZi0wMjk3LTRiN2ItYjYyNi0xYzFiNzFjZTVhNjQiLCJlbWFpbCI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwicm9sZSI6InJlZ2lzdGVyZWQiLCJpYXQiOjE3MzY0NTM1NTcsImV4cCI6MTczNjQ1NzE1NywiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.gKT49JEaEDp9_nlYs7wsmBEcFZfI0ukMG2gF46k9z90%22%2C%22refreshToken%22%3A%22eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiMTJhODIwZi0wMjk3LTRiN2ItYjYyNi0xYzFiNzFjZTVhNjQiLCJyZWZyZXNoVG9rZW5JZCI6IjI3YzMwZDI5LWFmYTEtNGQyOS1iZjA4LTE4ZWFkZWQ0YzZlZiIsImlhdCI6MTczNjQ1MzU1NywiZXhwIjoxNzM2NTM5OTU3LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.BjX0YDeZoFSKTzA9MSgs-cRvHuklSkgOM6klDrmKJNM%22%7D; Path=/; HttpOnly; Secure; SameSite=Strict