GET http://localhost:3002/fullUserInfo/646e98aa-7f87-4aff-9795-0e8ee2e03db5
Cookie: accessToken=j%3A%7B%22accessToken%22%3A%22eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDZlOThhYS03Zjg3LTRhZmYtOTc5NS0wZThlZTJlMDNkYjUiLCJlbWFpbCI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzM1ODMyMzAxLCJleHAiOjE3MzU4MzU5MDEsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.7CP887ZnAS0HkdJm9V-sPue3LrQLcbRggEpYf5MRCl0%22%2C%22refreshToken%22%3A%22eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDZlOThhYS03Zjg3LTRhZmYtOTc5NS0wZThlZTJlMDNkYjUiLCJyZWZyZXNoVG9rZW5JZCI6ImIyMzNlYjI1LTg3NjUtNDI4OS05MDk0LWY4MTg0NmE2OGFkMCIsImlhdCI6MTczNTgzMjMwMSwiZXhwIjoxNzM1OTE4NzAxLCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.ney0YGeOJzA4vi9Y65G8MCzeGDSNaWzEYowrpl5L0tQ%22%7D; Path=/; HttpOnly; Secure; SameSite=Strict