GET http://localhost:3002/refresh-tokens
Cookie: accessToken=j%3A%7B%22accessToken%22%3A%22eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhYTNkZWIzOC1kMWQyLTQ3ZTMtODE3OC03ZGE0YmJlYzVhMzIiLCJlbWFpbCI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwiaWF0IjoxNzM1ODI1OTM5LCJleHAiOjE3MzU4Mjk1MzksImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.f42YBAarzHKs84g4muDt29PTdb-LPV-0V9Wjhit2RhA%22%2C%22refreshToken%22%3A%22eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhYTNkZWIzOC1kMWQyLTQ3ZTMtODE3OC03ZGE0YmJlYzVhMzIiLCJyZWZyZXNoVG9rZW5JZCI6IjBhN2I5MDUzLTMzY2EtNGJiMy1hNzY1LTI5ZTk5YWMwNDJjMiIsImlhdCI6MTczNTgyNTkzOSwiZXhwIjoxNzM1OTEyMzM5LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.Z1Ur0YzAAZEoMVG2it8VDSAxe6kVQWwc1jYC8_WsG00%22%7D; Path=/; HttpOnly; Secure; SameSite=Strict