GET http://localhost:3002/refresh-tokens
Cookie: accessToken=j%3A%7B%22accessToken%22%3A%22eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiNjY1NGJjMy1kMWZiLTQ1YmEtOTVlNS1hMzlhYjFkN2VjYzQiLCJlbWFpbCI6ImpvaG4uZG9lMkBleGFtcGxlLmNvbSIsImlhdCI6MTczNTgwODg2OSwiZXhwIjoxNzM1ODEyNDY5LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.YNW3ae4KQjEUsklt5Gx2UvxgV07SVvFXbGVTzm5Fw1U%22%2C%22refreshToken%22%3A%22eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiNjY1NGJjMy1kMWZiLTQ1YmEtOTVlNS1hMzlhYjFkN2VjYzQiLCJpYXQiOjE3MzU4MDg4NjksImV4cCI6MTczNTg5NTI2OSwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.vAnTI_-mdhEVsybJhDD6JekQ5z7L9_Tl5MDnQg4IBZk%22%7D; Path=/; HttpOnly; Secure; SameSite=Strict