POST http://localhost:3001/actions
Content-Type: application/json

{
  "title": "Reclutamiento de Voluntarios",
  "description": "Buscar voluntarios para asistir en la distribución de alimentos.",
  "cause": "6783189fbb3ccffb18933e05",
  "type": "volunteer",
  "volunteerGoalCount": 20
}

