POST http://localhost:3001/actions
Content-Type: application/json

{
  "title": "Distribución de Leche",
  "description": "Recolectar y distribuir leche para comunidades vulnerables.",
  "cause": "677ee39918263ddcbcbfc890",
  "type": "food",
  "foodType": "leche",
  "foodGoalQuantity": 1000
}
