POST http://localhost:3001/actions
Content-Type: application/json

{
  "title": "Distribución de Leche",
  "description": "Recolectar y distribuir leche para comunidades vulnerables.",
  "cause": "6782ffd1bb3ccffb18933dda",
  "type": "food",
  "foodType": "leche",
  "foodGoalQuantity": 1000
}
