name: Deploy to EC2

on:
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.11

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init
        working-directory: ./ci-cd/terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve -var "ami_id=${{ secrets.AMI_ID }}" -var "instance_type=${{ secrets.INSTANCE_TYPE }}" -var "key_name=${{ secrets.KEY_NAME }}"
        working-directory: ./ci-cd/terraform

      - name: Inspect Terraform Output
        run: |
          terraform output public_ip
        working-directory: ./ci-cd/terraform

      - name: Get EC2 Public IP
        id: get_ec2_ip
        run: |
          # Clean the Terraform output and extract only the public IP address
          EC2_PUBLIC_IP=$(terraform output public_ip | grep -oP '\d+\.\d+\.\d+\.\d+')
          echo "Retrieved IP: $EC2_PUBLIC_IP"
          echo "EC2_PUBLIC_IP=$EC2_PUBLIC_IP" >> $GITHUB_ENV
        working-directory: ./ci-cd/terraform

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy files to EC2
        run: |
          echo "IP is $EC2_PUBLIC_IP"
          scp -r -o StrictHostKeyChecking=no . ec2-user@$EC2_PUBLIC_IP:/home/ec2-user

      - name: Create .env file on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ env.EC2_PUBLIC_IP }} "echo '$EC2_PUBLIC_IP' > /home/ec2-user/.env"

      - name: Run Docker Compose on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@$EC2_PUBLIC_IP "cd /home/ec2-user/ && sudo docker-compose up -d --build"
