name: Deploy to EC2

on:
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy files to EC2
        run: |
          scp -r -o StrictHostKeyChecking=no . ec2-user@3.91.10.241:/home/ec2-user

      - name: Create .env file on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@3.91.10.241 "echo '${{ secrets.ENV }}' > /home/ec2-user/.env"

      - name: Run Docker Compose on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@3.91.10.241 "cd /home/ec2-user/ && sudo docker-compose up -d --build"
